name: form_builder

ignore:
  - packages/**/example

packages:
  - packages/**

dev_dependencies:
  flutter_lints: ^1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"

scripts:
  analyze: melos exec -- pub global run tuneup check

  format: melos exec -- flutter format .

  test: >
    melos exec -c 1 --fail-fast --dir-exists=test --ignore="*example*" -- \
      flutter test test

  translate: melos exec --depends-on="intl_utils" -- flutter pub run intl_utils:generate
