name: Form Builder Phone Field

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - 'form_builder_phone_field-v*'
    branches: [master]
    paths:
      - "packages/form_builder_phone_field/**"
      - ".github/workflows/form_builder_phone_field.yaml"

  pull_request:
    branches: [master]
    paths:
      - "packages/form_builder_phone_field/**"
      - ".github/workflows/form_builder_phone_field.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [stable, beta]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - name: Run Tests
        run: |
          pushd packages/form_builder_phone_field
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter analyze --no-pub
          flutter test --no-pub --coverage

      - name: Build Example
        run: |
          pushd packages/form_builder_phone_field/example
          flutter build appbundle --no-pub --debug
          flutter build ios --no-pub --debug --no-codesign
          flutter build web --no-pub

      - name: Check publish warnings
        run: |
          pushd packages/form_builder_phone_field
          dart pub publish --dry-run

      - name: Upload coverage to Codecov
        if: ${{ matrix.channel == 'stable' }}
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          flags: unittests
          name: form_builder_phone_field

  deployment:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    name: Deploy package
    runs-on: ubuntu-latest

    steps:
    - name: Configure enviroment
      uses: actions/checkout@v3
    - name: Download flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Setup pub credentials
      shell: bash
      env:
        PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
        PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      run: |
        sh ./tools/pub_login.sh
    - name: Publish package
      run: |
          pushd packages/form_builder_phone_field
          dart pub publish -v -f
